public class CepInvalidException extends Exception {

}
// minha excessão do CEP

/*
 * EXPLICANDO O CÓDIGO
 * AQUI EU CRIO MINHA EXCEPTION PARA PODER APRESENTAR MEU ERRO
 * EU CRIO UMA CLASSE APENAS PARA O MEU USUÁRIO OU O MEU PROGRAMADOR TER QUE
 * TRATAR A EXCEÇÃO
 * 
 * AQUI EU CRIO A MINHA CLASSE COM O NOME DO DOCUMENTO DE FORMA NEGATIVA
 * COLOCANDO "INVALID" E NO FINAL COLOCOU UM EXEPTION PARA SER NOTAVEL QUE E
 * PARA TRATAR EXCEÇÕES
 * 
 * NA PARTE DE EXTENDS, EU DIGO QUE ELE VAI ESTENDER A ALGO, PODERIA ESTENDER
 * PARA UNEXCEPTION OU TANTO PARA EXCEPTION
 * 
 */